### ISSUE TITLE
Login without oidc.web3-login.net domain

### ISSUE THREAD

**Issue by ddon** [web3-login/web3-login#1]
thanks for your project, pretty cool... what if in the future you will not renew the domain, or something happens with your hosting, and all our logins will break. is there a way to host oidc.web3-login.net stuff on our end?

**Comment by chriamue** [comment]
Thank you for your question. It is a good question and one that definitely warrants further documentation.

The web3-login is an OpenID Connect (OIDC) server, which means that anyone can host it on their own servers. This means that if the domain for the current server were to expire, the OIDC server could be hosted on a different domain and configured to work with the same client.

In order to do this, the new domain would need to be configured in the OpenID Connect client. This would typically involve updating the client's configuration to point to the new server's domain.

Overall, the ability to host the OIDC server on your own servers gives you more control over the authentication process and can help ensure that your login process remains stable and reliable.

The Authorize URI on this example config has to be replaced by the servers domain. https://web3-login.net/#/config

**Comment by chriamue** [comment]
@ddon added your question to the faqs https://github.com/web3-login/web3-login#frequently-asked-questions-faqs
